### ISSUE TITLE
Diagnostico General del sistema.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/administrativa_mid_api#202]
Validar funcionalidades del sistema implementadas en la versión de desarrollo.

- [ ] Funcionalidades generales del sistema.

- [ ] Dejar los documentos publicos en nuxeo después de la aprobación del pago.

- [x] Inserción de metadatos a documentos.

- [x] Servicio para la trazabilidad de aprobaciones de oficios de cumplidos.

**Comment by diagutierrezro** [comment]
Junto a @AlaskaRising se verificó con el usuario pruebasoas2, el cual tiene rol de ordenador de gasto, las funcionalidades de aprobar, rechazar y ver documentos obteniendo el siguiente error al aprobar o rechazar los documentos cargados:

![WhatsApp Image 2020-10-20 at 11 08 56 AM](https://user-images.githubusercontent.com/38676533/96627346-526b5800-12d6-11eb-9942-52361d9dc94e.jpeg)

Se identifica que este error es causado por la falta de una tabla en administrativa_crud_api por lo que se procede a hablar con DBAs para añadir esta tabla al ambiente de test, una vez DBA realiza este cambio procedemos a validar de nuevo pero ahora aparece un nuevo error de integridad:

![CAPTURA 1](https://user-images.githubusercontent.com/38676533/96627604-bbeb6680-12d6-11eb-82a9-0212e13eecab.PNG)

El día de hoy en el daily se le informa al líder técnico @ddguerra90 y se le solicita la gestión para poder ver los datos en la BD ya que en este momento no se tiene acceso, es posible que en la tabla que se creó por los DBA no se hayan migrado los datos.

**Comment by ddguerra90** [comment]
Se hizo la petición a los DBA, los cuales informaron que la tabla "cambio_estado_pago" solo estaba en test, y al sincronizarse no aparecía. Se corrige el error con la ayuda de los DBA y se procede a revisar el sistema el cual presenta un nuevo error de "llave duplicada", esto debido a que es posible que el valor de la secuencia esta atrasado con respecto a los datos. Se informa nuevamente a los DBA quienes corrigen el error.

Se suministra al equipo las credenciales para acceder al sistema de cumplidos con el rol de supervisor

pruebasoas
Dev3l0p2020

**Comment by diagutierrezro** [comment]
El día de hoy se reciben las credenciales para acceder al sistema de cumplidos con el rol de supervisor con las cuales se realizan las pruebas en el respectivo rol.
Junto a @AlaskaRising se realiza todo el proceso de cumplidos  (desde la carga de documentos por parte del contratista hasta su rechazo y/o aprobación por parte del supervisor o aprobador de pago) se presenta el siguiente error:
- Al tener un contrato para aprobar o rechazar como se muestra a continuación
![](https://cdn.discordapp.com/attachments/610144512789970956/768648141594558494/unknown.png)

al momento de rechazar o aprobar el contrato el proceso se efectúa de manera correcta, sin embargo se hace una petición a "administrativa_crud_api" en la tabla pago_mensual arrojando error 500 "Internal Server Error" como se muestra a continuación

![](https://cdn.discordapp.com/attachments/610144512789970956/768648371027050597/unknown.png)

Lo que ocasiona un mensaje de error

![](https://cdn.discordapp.com/attachments/610144512789970956/768648226026815488/unknown.png)

Está petición también se realiza al cargar los documentos por parte del contratista pero en este caso el mensaje de error no se muestra en la pantalla, es posible que el refactor del api administrativa_crud_api esté afectando las peticiones.

**Comment by diagutierrezro** [comment]
Se realiza el documento de cierre junto a @AlaskaRising  donde se realiza una explicación del diagnostico del sistema como se encontró en un inicio y los cambios realizados, el documento se encuentra en:
https://drive.google.com/file/d/1rtS32hsgk_66Q-TPm6wfzk3YkWzV2UJ2/view?usp=sharing
