### ISSUE TITLE
Revisión y análisis de modelos de datos de cumplidos y lineamientos oas

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/administrativa_mid_api#204]
Revisar la información suministrada sobre cumplidos y los modelos de base de datos
https://tuleap.portaloas.udistrital.edu.co/plugins/mediawiki/wiki/gaia/index.php?title=CUMPLIDOS

Revisar los lineamientos de construcción de modelos de datos suministrados por la OAS
https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md

Revisar los lineamientos de construcción de API MID suministrados por la OAS
https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/create_api_mid.md

**Comment by anndresfelipe29** [comment]
En compañía de @diagutierrezro se revisa la documentación existente sobre cumplidos para separarlo en un nuevo esquema independiente del esquema administrativa, además se revisa el código existente relacionado en las apis administrativa_crud, administrativa_mid y cliente de cumplidos, encontrando que:

- Al cambiar el esquema actual y consumirlo desde un nuevo crud, el cliente de cumplidos sufrirá fallos porque tiene código que apunta a las tablas de necesidades (que no necesita, ni se usan) en el esquema administrativa por medio de llamadas a **administrativa_crud** y que no estarán en el nuevo **cumplidos_crud**, por lo tanto se anuncia que esto debe ser corregido.
- Se establecen dos posibles diseños diseños para el nuevo modelo de datos de cumplidos, vistos a continuacion
**Modelo 1**
Modelo en funcionamiento, solo se agrega un campo de activo en la tabla **cambio_estado_pago**
![image](https://user-images.githubusercontent.com/30865375/98845462-c0a9c300-241b-11eb-9adf-201096137d40.png) 
**Modelo 2**
Se convierte la tabla **cambio_estado_pago** en una tabla de rompimiento y se eliminan atributos que se repiten en las tablas pago_mensual y cambio_estado_pago.
![image](https://user-images.githubusercontent.com/30865375/98848360-9e19a900-241f-11eb-917d-2bde0d76c343.png)
Se elige el modelo 1 por:
   - Permitir conservar el trabajo existente.
   - Permitir rehusar parte del código existente de **administrativa_crud** en cumplidos_crud y de **administrativa_mid_api** en cumplidos_mid.

Es de destacar que el código en **administrativa_crud** y **administrativa_mid_api** a reutilizar no sigue los lineamientos existentes en la oficina, por lo tanto este debe ser refactorizado.
