### ISSUE TITLE
Revisión y extracción de controladores administrativa_mid_api

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/administrativa_mid_api#205]
Revisar el funcionamiento de los controladores "aprobacion_pago.go" y "utilidades.go" de "administrativa_mid_api" para posteriormente implementarlas en la nueva api

**Comment by JuanCamiloMartinezLopez** [comment]
Se intento realizar un análisis de los controladores "aprobacion_pago.go", "utilidades.go" y "solicitud_necesidad" de "administrativa_mid_api",  se documentan los diferentes endpoints de los controladores y se deja un resumen de su parametros, funcionalidad y problemas.
[Revisión y extracción de controladores administrativa.pdf](https://github.com/udistrital/administrativa_mid_api/files/5513646/Revision.y.extraccion.de.controladores.administrativa.pdf)
