### ISSUE TITLE
Creación del nuevo modelo de base de datos

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/administrativa_mid_api#206]

**Comment by anndresfelipe29** [comment]
Para la creación del nuevo modelo de base de datos se consideran 2 propuestas eligiendo continuar con el modelo actual. Esto facilita los cambios a hacer. A continuación se muestra el modelo a implementar en la base de datos para cumplidos y sobre el cual se creara el nuevo crud de Cumplidos
![image](https://user-images.githubusercontent.com/30865375/98845462-c0a9c300-241b-11eb-9adf-201096137d40.png)

**Comment by nodier25** [comment]
Buenos días compañeros

Al modelo en las referencias fk de las tablas les faltan los lineamientos, por ejemplo en la tabla pago_mesual en el campo estado_pago_mesula le falta a lo ultimo _id ya que es un fk.

Tener encuenta el siguiente link donde estan los lineamientos https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md para que se puedan guiar. 

Por tal motivo no se a prueba el modelo, por favor  al subir el nuevo modelo corregio les agradecemos colocar las notas de los cambios que se hagan

Muchas gracias compañeros

**Comment by anndresfelipe29** [comment]
Se corrigen los errores dichos, ademas:
- Se verifican todos los lineamientos
- Se agregan las notas correspondientes cuando se hace referencia a tablas de otros esquemas y el sufijo _id en tales casos.
- Se agregan los campos de activo, fecha_creacion y fecha_modificacion a todas las tablas como se dice en los lineamientos.


![image](https://user-images.githubusercontent.com/30865375/99100684-2035d900-25aa-11eb-8fb2-e8da7196c024.png)


Queda pendiente una nueva revisión.
@nodier25  @fnrojash

**Comment by nodier25** [comment]
Buen día

Se a prueba el modelo por parte del DBAs ya que cumple con los lineamientos.

Muchas gracias

**Comment by anndresfelipe29** [comment]
Se modifican los campos nuevos   con el nombre **activo**, **fecha_creacion** y **fecha_modificacion** para que puedan ser campos nulos y se pueda migrar la información existente a este nuevo modelo sin problema. Se conserva la propiedad de **not null** en los campos **activo**, **fecha_creacion** y **fecha_modificacion** que ya existian en el modelo anterior.

![image](https://user-images.githubusercontent.com/30865375/99418325-e5dd7c00-28c8-11eb-99a1-cef4075c7e22.png)

**Comment by diagutierrezro** [comment]
Se crea el script de acuerdo al modelo de la base de datos

[cumplidos.zip](https://github.com/udistrital/administrativa_mid_api/files/5557007/cumplidos.zip)

**Comment by ddguerra90** [comment]
Se realizaron unos cambios en el script para la creación de la base de datos 

[cumplidos.zip](https://github.com/udistrital/administrativa_mid_api/files/5562890/cumplidos.zip)

**Comment by ddguerra90** [comment]
Se adjunta el script para llenar la base de datos 

[script_llenado_cumplidos_nuevo.zip](https://github.com/udistrital/administrativa_mid_api/files/5569013/script_llenado_cumplidos_nuevo.zip)
