### ISSUE TITLE
Creacion api_mid

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/administrativa_mid_api#207]
Creación del api mid para cumplidos teniendo en cuenta los lineamientos suministrados por la OAS

https://github.com/udistrital/lineamientos_oas#generaci%C3%B3n-api-mid

Repositorio para el api mid
https://github.com/udistrital/cumplidos_mid

Crear y validar los controladores para el correcto funcionamiento del api mid

- [x] Dockerizacion

**Comment by anndresfelipe29** [comment]
Se han agregado exitosamente los servicios:

- solicitudes_coordinador
- solicitudes_ordenador_contratistas
- aprobar_pagos
- solicitudes_ordenador
- dependencia_ordenador
- certificacion_documentos_aprobados
- contratos_contratistas
- certificacion_visto_bueno
- solicitudes_ordenador_contratistas_dependencia


Estos servicios son funcionales y ahora apuntan al crud de cumplidos cuando se usa este servicio. Además ya se entiende la lógica y próximamente se separara la lógica del servicio y se enviara a una carpeta de helpers para lograr la separación de responsabilidades.

**Comment by diagutierrezro** [comment]
- Se finalizó con la migración de los controladores hacia cumplidos_mid
- Se realizó la separación de la lógica de los controladores migrando esta lógica hacia los helpers.
Como paso a seguir, posteriormente se realizará el refactor del mid de cumplidos segun los lineamientos de la OAS

**Comment by ddguerra90** [comment]
Se realiza la solicitud de despliegue del api mid mediante el siguiente kanban
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39667

**Comment by ddguerra90** [comment]
Se realiza una solicitud para la corrección de una variable de entorno para el despliegue del api mid para cumplidos en el siguiente kamban: 
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39715

**Comment by diagutierrezro** [comment]
La separación de la logica de los servicios se realiza de la siguiente manera:

- Se creó una nueva carpeta helpers donde se agregaron todos los archivos que manejan la logica
![image](https://user-images.githubusercontent.com/38676533/103565517-762e4b00-4e8e-11eb-903d-a82d86569a8d.png)

- En los controladores solo se reciben los parametros que lleguen desde el cliente y se hace el llamado al helper correspondiente donde se encuentre la logica que necesitamos
![image](https://user-images.githubusercontent.com/38676533/103565604-9b22be00-4e8e-11eb-9a22-95c9aa501e95.png)
![image](https://user-images.githubusercontent.com/38676533/103565618-a249cc00-4e8e-11eb-8d23-380b6741494c.png)

- En los helpers se realiza todo el manejo de la logica y llamado a los otros servicios que se requieran para realizar la tarea correctamente
