### ISSUE TITLE
Propuesta de plan de trabajo - Migración de datos.

### ISSUE THREAD

**Issue by a52290451** [udistrital/administrativa_mid_api#221]
Adjuntar propuesta de plan de trabajo relacionada con la migración de la base de datos ORACLE académica a AURORA postgres.

**Criterio de aceptación**

- [x] Documento con propuesta de plan de trabajo contemplando actividades a desarrollar y estimación de tiempos.

**Comment by AlejaB18** [comment]
[Entregas de Valor Sp 1-3 Migracion.xlsx](https://github.com/udistrital/administrativa_mid_api/files/7221237/Entregas.de.Valor.Sp.1-3.Migracion.xlsx)

**Comment by a52290451** [comment]
[Plan de trabajo revisado.xlsx](https://github.com/udistrital/administrativa_mid_api/files/7239224/Plan.de.trabajo.revisado.xlsx)
